"""Add Phase 1 order notification queue

Revision ID: 787b0afc03ab
Revises: 091ae9e801ad
Create Date: 2026-09-29 16:15:48.214201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787b0afc03ab'
down_revision = '091ae9e801ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('recipient', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=160), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('attempts >= 0', name='ck_order_notifications_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'channel', 'event', name='uq_order_notification_event')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_notifications')
    # ### end Alembic commands ###
