"""Add WhatsApp consent and delivery retry state

Revision ID: e198d1915508
Revises: 787b0afc03ab
Create Date: 2026-09-29 19:13:26.591657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e198d1915508'
down_revision = '787b0afc03ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('whatsapp_opt_in_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('whatsapp_opt_in', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_opt_in_at')
        batch_op.drop_column('whatsapp_opt_in')

    with op.batch_alter_table('order_notifications', schema=None) as batch_op:
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('next_attempt_at')

    # ### end Alembic commands ###
